### ISSUE TITLE
Powershell profile is not used? TLS12 issue

### ISSUE THREAD

**Issue by Lechus** [JetBrains/teamcity-powershell#2]
Have to add support for TLS12 in powershell so set it up in PS profile file.
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`
Although it works when executing script from cmd or ps console, TC executing script still gives error:
`The request was aborted: Could not create SSL/TLS secure channel.`

How to set PS Profile:
https://www.howtogeek.com/50236/customizing-your-powershell-profile/

Installed Powershell CORE, but it is not seen by Agents?

**Comment by orybak** [comment]
In PowerShell step settings, do you have "use NoProfile" checkbox checked? If so, the profile will not be loaded. Could you please uncheck it and try again?

**Comment by Lechus** [comment]
Thanks. Missed it.
