### ISSUE TITLE
PowerShell Desktop detection broken

### ISSUE THREAD

**Issue by xevantus** [JetBrains/teamcity-powershell#3]
Plugin is no longer detecting the `powershell.exe` file used by non-Core versions of PowerShell.

Even though the search paths are configurable, detection only looks for `pwsh.exe`.  The only workaround for this issue is to manually create a symbolic link within a protected system directory.

**Comment by JuliaResh** [comment]
@xevantus Which TeamCity version do you use? Could you please create an issue in the TeamCity issues tracker: https://youtrack.jetbrains.com/issues/TW and attach 'teamcity-agent.log' with debug level on covering the time of the agent restart?

**Comment by ricohomewood** [comment]
Having the same issue. See related bug: https://github.com/JetBrains/teamcity-docker-minimal-agent/issues/31

This is on server version 2019.2.2

This issue has the attached teamcity-agent.log. This is the issue:

**[2020-04-01 12:55:21,209] INFO - Server.powershell.agent.DETECT - No PowerShell detected. If it is installed in non-standard location, please provide install locations in teamcity.powershell.detector.search.paths agent property (with ';' as a separator)**
[2020-04-01 12:55:21,252] INFO - .agent.AgentStartupGitDetector - Detect git at /usr/bin/git
[2020-04-01 12:55:21,263] WARN - r.mono.MonoPropertiesExtension - Failed to start pkg-config. Cannot run program "pkg-config": error=2, No such file or directory

**Comment by JuliaResh** [comment]
@ricohomewood Which docker tag do you use to start the agent?

**Comment by xevantus** [comment]
Root cause of this for us was due to the Docker incompatibility with the Feb 2020 secuirty patch, which was causing any use of the Windows Registry to fail.   However, registry discovery aside, the file system discovery is currently looking for a file that will never exist (e.g. `C:\Windows\System32\WindowsPowerShell\v1. 0\pwsh.exe`).

**Comment by JuliaResh** [comment]
@xevantus Thank you for the information about the security patch. Indeed there are two PowerShell detectors: one uses registry and detects Desktop version only, and another looks into the file system and detects Core version only.
Is it possible that teamcity.powershell.detector.search.paths property points to the `C:\Windows\System32\WindowsPowerShell\v1.0\` directory?

**Comment by xevantus** [comment]
@JuliaResh We don't set that parameter manually, and I don't see it set on the agent at all.  
I see a comment in `DetectionPaths` saying nanoserver installs PS Core in the same location as PS Desktop for other versions.  So in that single case, the checked path _would_ be valid.

> one uses registry and detects Desktop version only, and another looks into the file system and detects Core version only.

That makes sense, but I can't find it documented anywhere, hence the confusion.  Until recently we were using an older version of the plugin that _was_ checking for `powershell.exe`.

**Comment by orybak** [comment]
File system discovery was implemented to support Core version only. I have made a fix for 2019.x branch of TeamCity (https://github.com/JetBrains/teamcity-powershell/commit/d35fd887164f2d164d6a1b88ddb21f96a2ee84df) that implements PowerShell Desktop detection through command line. Also adds a possibility to specify custom paths for PowerShell Desktop through 'teamcity.powershell.detector.search.paths' property.

Please see attached plugin here: https://youtrack.jetbrains.com/issue/TW-65122#focus=streamItem-27-4065552.0-0

**Comment by orybak** [comment]
@xevantus In older verisions both PowerShell Desktop and Core had executables named 'powershell.exe'. That is why Desktop version could be detected alongside Core through the file system (although it never meant to be detected intentionally)
